### PR TITLE
Handle "ear.veraison.key-attestation" on deserialisation

### LINKED ISSUE #7: BUG: `Unable to process attestation result` when carrying Veraison's "key attestation" claims
Running:

```rust
let ear = Ear::from_jwt(    // Ear comes from rust-ear
    &attestation_result,
    jwt::Algorithm::ES256,  // jwt comes from jsonwebtoken
    &jwt::DecodingKey::from_ec_pem(
        verification_api
            .ear_verification_key_as_pem()
            .unwrap()
            .as_bytes()
    ).unwrap()
);

let ear = match ear {
    Err(e) => {
        println!("Unable to process attestation result ({})", e);
        return -1
    },
    Ok(r) => r,
};
```

Using:

* [EAR JWT](https://github.com/veraison/rust-ear/files/13902060/Guilhem-ka-de-failure.jwt.txt)
* [Verification key](https://github.com/veraison/rust-ear/files/13902059/Guilhem-ka-de-failure.pem.txt)

Returns:

```
Unable to process attestation result (verify error: JSON error: expected `,` or `}` at line 1 column 1382)
```

Reported by @gbryant-arm

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fix #7

/cc @gbryant-arm

### CODE REVIEW

File: src/appraisal.rs [hunk 1]
```diff
@@ -146,6 +146,9 @@ impl<'de> Visitor<'de> for AppraisalVisitor {
         loop {
             if self.is_human_readable {
                 match map.next_key::<&str>()? {
+                    Some("ear.veraison.key-attestation") => {
+                        appraisal.key_attestation = Some(map.next_value::<KeyAttestation>()?)
+                    }
```
Comment (setrofim) [inline src/appraisal.rs:151]: Also need the corresponding `Some(-70002)` entry on the `else` (non human readable) arm.

**Review by setrofim — CHANGES_REQUESTED** [review]

File: src/appraisal.rs (hunk 1 above)
Comment (thomas-fossati) [reply src/appraisal.rs]: see [28ba101](https://github.com/veraison/rust-ear/pull/8/commits/28ba10181b3918c0c5c05daac872e82429a1d14a)

**Review by setrofim — APPROVED** [review]
LGTM!
